//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentsInitParameters) DeepCopyInto(out *AttachmentsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentsInitParameters.
func (in *AttachmentsInitParameters) DeepCopy() *AttachmentsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AttachmentsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentsObservation) DeepCopyInto(out *AttachmentsObservation) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeName != nil {
		in, out := &in.SizeName, &out.SizeName
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentsObservation.
func (in *AttachmentsObservation) DeepCopy() *AttachmentsObservation {
	if in == nil {
		return nil
	}
	out := new(AttachmentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentsParameters) DeepCopyInto(out *AttachmentsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentsParameters.
func (in *AttachmentsParameters) DeepCopy() *AttachmentsParameters {
	if in == nil {
		return nil
	}
	out := new(AttachmentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldInitParameters) DeepCopyInto(out *FieldInitParameters) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(string)
		**out = **in
	}
	if in.Linked != nil {
		in, out := &in.Linked, &out.Linked
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldInitParameters.
func (in *FieldInitParameters) DeepCopy() *FieldInitParameters {
	if in == nil {
		return nil
	}
	out := new(FieldInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldObservation) DeepCopyInto(out *FieldObservation) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(string)
		**out = **in
	}
	if in.Linked != nil {
		in, out := &in.Linked, &out.Linked
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldObservation.
func (in *FieldObservation) DeepCopy() *FieldObservation {
	if in == nil {
		return nil
	}
	out := new(FieldObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldParameters) DeepCopyInto(out *FieldParameters) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(string)
		**out = **in
	}
	if in.Linked != nil {
		in, out := &in.Linked, &out.Linked
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldParameters.
func (in *FieldParameters) DeepCopy() *FieldParameters {
	if in == nil {
		return nil
	}
	out := new(FieldParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Login) DeepCopyInto(out *Login) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Login.
func (in *Login) DeepCopy() *Login {
	if in == nil {
		return nil
	}
	out := new(Login)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Login) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginInitParameters) DeepCopyInto(out *LoginInitParameters) {
	*out = *in
	if in.CollectionIds != nil {
		in, out := &in.CollectionIds, &out.CollectionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Favorite != nil {
		in, out := &in.Favorite, &out.Favorite
		*out = new(bool)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = make([]FieldInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.Reprompt != nil {
		in, out := &in.Reprompt, &out.Reprompt
		*out = new(bool)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = make([]URIInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginInitParameters.
func (in *LoginInitParameters) DeepCopy() *LoginInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoginInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginList) DeepCopyInto(out *LoginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Login, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginList.
func (in *LoginList) DeepCopy() *LoginList {
	if in == nil {
		return nil
	}
	out := new(LoginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginObservation) DeepCopyInto(out *LoginObservation) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]AttachmentsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CollectionIds != nil {
		in, out := &in.CollectionIds, &out.CollectionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = new(string)
		**out = **in
	}
	if in.DeletedDate != nil {
		in, out := &in.DeletedDate, &out.DeletedDate
		*out = new(string)
		**out = **in
	}
	if in.Favorite != nil {
		in, out := &in.Favorite, &out.Favorite
		*out = new(bool)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = make([]FieldObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.Reprompt != nil {
		in, out := &in.Reprompt, &out.Reprompt
		*out = new(bool)
		**out = **in
	}
	if in.RevisionDate != nil {
		in, out := &in.RevisionDate, &out.RevisionDate
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(float64)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = make([]URIObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginObservation.
func (in *LoginObservation) DeepCopy() *LoginObservation {
	if in == nil {
		return nil
	}
	out := new(LoginObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginParameters) DeepCopyInto(out *LoginParameters) {
	*out = *in
	if in.CollectionIds != nil {
		in, out := &in.CollectionIds, &out.CollectionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Favorite != nil {
		in, out := &in.Favorite, &out.Favorite
		*out = new(bool)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = make([]FieldParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotesSecretRef != nil {
		in, out := &in.NotesSecretRef, &out.NotesSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Reprompt != nil {
		in, out := &in.Reprompt, &out.Reprompt
		*out = new(bool)
		**out = **in
	}
	if in.TotpSecretRef != nil {
		in, out := &in.TotpSecretRef, &out.TotpSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = make([]URIParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginParameters.
func (in *LoginParameters) DeepCopy() *LoginParameters {
	if in == nil {
		return nil
	}
	out := new(LoginParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginSpec) DeepCopyInto(out *LoginSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginSpec.
func (in *LoginSpec) DeepCopy() *LoginSpec {
	if in == nil {
		return nil
	}
	out := new(LoginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginStatus) DeepCopyInto(out *LoginStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginStatus.
func (in *LoginStatus) DeepCopy() *LoginStatus {
	if in == nil {
		return nil
	}
	out := new(LoginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNote) DeepCopyInto(out *SecureNote) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNote.
func (in *SecureNote) DeepCopy() *SecureNote {
	if in == nil {
		return nil
	}
	out := new(SecureNote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureNote) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteAttachmentsInitParameters) DeepCopyInto(out *SecureNoteAttachmentsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteAttachmentsInitParameters.
func (in *SecureNoteAttachmentsInitParameters) DeepCopy() *SecureNoteAttachmentsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecureNoteAttachmentsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteAttachmentsObservation) DeepCopyInto(out *SecureNoteAttachmentsObservation) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(string)
		**out = **in
	}
	if in.SizeName != nil {
		in, out := &in.SizeName, &out.SizeName
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteAttachmentsObservation.
func (in *SecureNoteAttachmentsObservation) DeepCopy() *SecureNoteAttachmentsObservation {
	if in == nil {
		return nil
	}
	out := new(SecureNoteAttachmentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteAttachmentsParameters) DeepCopyInto(out *SecureNoteAttachmentsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteAttachmentsParameters.
func (in *SecureNoteAttachmentsParameters) DeepCopy() *SecureNoteAttachmentsParameters {
	if in == nil {
		return nil
	}
	out := new(SecureNoteAttachmentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteFieldInitParameters) DeepCopyInto(out *SecureNoteFieldInitParameters) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(string)
		**out = **in
	}
	if in.Linked != nil {
		in, out := &in.Linked, &out.Linked
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteFieldInitParameters.
func (in *SecureNoteFieldInitParameters) DeepCopy() *SecureNoteFieldInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecureNoteFieldInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteFieldObservation) DeepCopyInto(out *SecureNoteFieldObservation) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(string)
		**out = **in
	}
	if in.Linked != nil {
		in, out := &in.Linked, &out.Linked
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteFieldObservation.
func (in *SecureNoteFieldObservation) DeepCopy() *SecureNoteFieldObservation {
	if in == nil {
		return nil
	}
	out := new(SecureNoteFieldObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteFieldParameters) DeepCopyInto(out *SecureNoteFieldParameters) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(string)
		**out = **in
	}
	if in.Linked != nil {
		in, out := &in.Linked, &out.Linked
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteFieldParameters.
func (in *SecureNoteFieldParameters) DeepCopy() *SecureNoteFieldParameters {
	if in == nil {
		return nil
	}
	out := new(SecureNoteFieldParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteInitParameters) DeepCopyInto(out *SecureNoteInitParameters) {
	*out = *in
	if in.CollectionIds != nil {
		in, out := &in.CollectionIds, &out.CollectionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Favorite != nil {
		in, out := &in.Favorite, &out.Favorite
		*out = new(bool)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = make([]SecureNoteFieldInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.Reprompt != nil {
		in, out := &in.Reprompt, &out.Reprompt
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteInitParameters.
func (in *SecureNoteInitParameters) DeepCopy() *SecureNoteInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecureNoteInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteList) DeepCopyInto(out *SecureNoteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecureNote, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteList.
func (in *SecureNoteList) DeepCopy() *SecureNoteList {
	if in == nil {
		return nil
	}
	out := new(SecureNoteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecureNoteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteObservation) DeepCopyInto(out *SecureNoteObservation) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]SecureNoteAttachmentsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CollectionIds != nil {
		in, out := &in.CollectionIds, &out.CollectionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = new(string)
		**out = **in
	}
	if in.DeletedDate != nil {
		in, out := &in.DeletedDate, &out.DeletedDate
		*out = new(string)
		**out = **in
	}
	if in.Favorite != nil {
		in, out := &in.Favorite, &out.Favorite
		*out = new(bool)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = make([]SecureNoteFieldObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(string)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.Reprompt != nil {
		in, out := &in.Reprompt, &out.Reprompt
		*out = new(bool)
		**out = **in
	}
	if in.RevisionDate != nil {
		in, out := &in.RevisionDate, &out.RevisionDate
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteObservation.
func (in *SecureNoteObservation) DeepCopy() *SecureNoteObservation {
	if in == nil {
		return nil
	}
	out := new(SecureNoteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteParameters) DeepCopyInto(out *SecureNoteParameters) {
	*out = *in
	if in.CollectionIds != nil {
		in, out := &in.CollectionIds, &out.CollectionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Favorite != nil {
		in, out := &in.Favorite, &out.Favorite
		*out = new(bool)
		**out = **in
	}
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = make([]SecureNoteFieldParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NotesSecretRef != nil {
		in, out := &in.NotesSecretRef, &out.NotesSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(string)
		**out = **in
	}
	if in.Reprompt != nil {
		in, out := &in.Reprompt, &out.Reprompt
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteParameters.
func (in *SecureNoteParameters) DeepCopy() *SecureNoteParameters {
	if in == nil {
		return nil
	}
	out := new(SecureNoteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteSpec) DeepCopyInto(out *SecureNoteSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteSpec.
func (in *SecureNoteSpec) DeepCopy() *SecureNoteSpec {
	if in == nil {
		return nil
	}
	out := new(SecureNoteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureNoteStatus) DeepCopyInto(out *SecureNoteStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureNoteStatus.
func (in *SecureNoteStatus) DeepCopy() *SecureNoteStatus {
	if in == nil {
		return nil
	}
	out := new(SecureNoteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URIInitParameters) DeepCopyInto(out *URIInitParameters) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URIInitParameters.
func (in *URIInitParameters) DeepCopy() *URIInitParameters {
	if in == nil {
		return nil
	}
	out := new(URIInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URIObservation) DeepCopyInto(out *URIObservation) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URIObservation.
func (in *URIObservation) DeepCopy() *URIObservation {
	if in == nil {
		return nil
	}
	out := new(URIObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URIParameters) DeepCopyInto(out *URIParameters) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URIParameters.
func (in *URIParameters) DeepCopy() *URIParameters {
	if in == nil {
		return nil
	}
	out := new(URIParameters)
	in.DeepCopyInto(out)
	return out
}
